2011:
    # common config
    common:
        grl: 'grl/2011/current.xml'
    # lephad config
    lh:
        mc_path: '/cluster/data03/michel/mc11'
        mc_prefix: 'group.phys-higgs.LHSkim'
        mc_pattern: '*.root*'
        mc_treename: 'tau'
        mc_sampletype: 'standard'
        data_path: '/cluster/data01/michel/data11/all'
        data_prefix: 'group.phys-higgs.LHSkim'
        data_pattern: '*.root*'
        data_treename: 'tau'
        data_sampletype: 'standard'
        embed_path: '/cluster/data05/michel/Ntuples/Ztautau_embedded11'
        embed_prefix: 'group.phys-higgs.LHSkim'
        embed_pattern: '*.root*'
        embed_treename: 'tau'
        embed_sampletype: 'standard'
    # hadhad config
    hh:
        mc_path: '/global/common/higgstautau/skims/hadhad/newskims'
        mc_prefix: 'group.phys-higgs.hhskim'
        mc_pattern: '*hadhad.root*'
        mc_treename: 'tau'
        mc_sampletype: 'standard'
        data_path: '/global/common/higgstautau/skims/hadhad/newskims'
        data_prefix: 'group.phys-higgs.hhskim'
        data_pattern: '*hadhad.root*'
        data_treename: 'tau'
        data_sampletype: 'standard'
        embed_path: '/global/common/higgstautau/skims/hadhad/newskims'
        embed_prefix: 'group.phys-higgs.hhskim'
        embed_pattern: '*.root*'
        embed_treename: 'tau'
        embed_sampletype: 'standard'
2012:
    # common config
    common:
        grl: 'grl/2012/current.xml'
    hh:
        mc_path: '/global/common/higgstautau/skims/hadhad/newskims'
        mc_prefix: 'group.phys-higgs.hhskim'
        mc_pattern: '*hadhad.root*'
        mc_treename: 'tau'
        mc_sampletype: 'standard'
        data_path: '/global/common/higgstautau/skims/hadhad/newskims'
        data_prefix: 'group.phys-higgs.hhskim'
        data_pattern: '*hadhad.root*'
        data_treename: 'tau'
        data_sampletype: 'standard'
        embed_path: '/global/common/higgstautau/skims/hadhad/newskims'
        embed_prefix: 'group.phys-higgs.hhskim'
        embed_pattern: '*embedding12_ztautau_hh_p1131.root*'
        embed_treename: 'tau'
        embed_sampletype: 'standard'
    lh:
        mc_path: '/global/mtm/lhCN-2012/mc12'
        mc_prefix: 'group.phys-higgs'
        mc_pattern: '*.root*'
        mc_treename: 'tau'
        mc_sampletype: 'lhCN'
        data_path: '/global/mtm/lhCN-2012/data12'
        data_prefix: 'group.phys-higgs'
        data_pattern: '*.root*'
        data_treename: 'tau'
        data_sampletype: 'lhCN'
        embed_path: '/global/mtm/lhCN-2012/embed12'
        embed_prefix: 'group.phys-higgs'
        embed_pattern: '*.root*'
        embed_treename: 'tau'
        embed_sampletype: 'lhCN'
